import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProviderWrapper } from "./SessionProviderWrapper";
import NavbarComponent from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Login Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <NavbarComponent />
          <main className="flex-1">
            <SessionProviderWrapper>{children}</SessionProviderWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}
